Models/Breed.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using AnimalShop.Context;

namespace AnimalShop.Models
{
    public class Breed
    {
        public Int64 BreedID { get; set; }

        public string BreedType { get; set; }

        [Display(Name = "Created Date")]


        public DateTime? CreatedAt { get; set; }
        [Display(Name = "Updated Date")]

        public DateTime? UpdatedAt { get; set; }


        public bool BreedAlReadyExists(AnimalDbContext db, Breed breed)
        {

            var dbbreed = db.Breeds.SingleOrDefault(b => b.BreedType == breed.BreedType);

            if (dbbreed == null)
            {
                return false;
            }
            else
            {
                return true;
            }


        }


    }
}

Areas/Admin/Controllers/BreedController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AnimalShop.Context;
using AnimalShop.Models;

namespace AnimalShop.Areas.Admin.Controllers
{
    public class BreedController : Controller
    {
        private AnimalDbContext db = new AnimalDbContext();

        // GET: Admin/Breed
        public async Task<ActionResult> Index()
        {
            return View(await db.Breeds.ToListAsync());
        }

        // GET: Admin/Breed/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Breed breed = await db.Breeds.FindAsync(id);
            if (breed == null)
            {
                return HttpNotFound();
            }
            return View(breed);
        }

        // GET: Admin/Breed/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Breed/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "BreedID,BreedType,CreatedAt,UpdatedAt")] Breed breed)
        {
            if (ModelState.IsValid)
            {



                if (new Breed().BreedAlReadyExists(db, breed))

                {
                    ViewBag.MSG = "Breed Already Exists!";
                    return View("Create", breed);
                }
                else if (String.IsNullOrEmpty(breed.BreedType))
                {
                    ViewBag.MSG = "Please  Provide Breed Type";
                    return View("Create", breed);
                }
                else
                {


                    breed.CreatedAt = DateTime.Now;
                    breed.UpdatedAt = DateTime.Now;

                    db.Breeds.Add(breed);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }




            }

            return View(breed);
        }

        // GET: Admin/Breed/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Breed breed = await db.Breeds.FindAsync(id);
            if (breed == null)
            {
                return HttpNotFound();
            }
            return View(breed);
        }

        // POST: Admin/Breed/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "BreedID,BreedType,CreatedAt,UpdatedAt")] Breed breed)
        {
            if (ModelState.IsValid)
            {
                var dbBreed = db.Breeds.SingleOrDefault(m => m.BreedID == breed.BreedID);

                dbBreed.BreedType = breed.BreedType;
                dbBreed.UpdatedAt = DateTime.Now;

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(breed);
        }

        // GET: Admin/Breed/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Breed breed = await db.Breeds.FindAsync(id);
            if (breed == null)
            {
                return HttpNotFound();
            }
            return View(breed);
        }

        // POST: Admin/Breed/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            Breed breed = await db.Breeds.FindAsync(id);
            db.Breeds.Remove(breed);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Breed/Create.cshtml
@model AnimalShop.Models.Breed

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


<div class="page-wrapper">
    <div class="card">
        <div class="card-body">
            <div>
                <label>
                    @if (ViewBag.MSG != null)
                    {
                        <h3>    @ViewBag.MSG</h3>
                    }
                </label>
            </div>


            @using (Html.BeginForm("Create", "Breed"))
            {

                @Html.AntiForgeryToken()

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-3">
                        <label>Add Breed </label>
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-3">
                        @Html.EditorFor(model => model.BreedType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BreedType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        <button type="submit" class="btn btn-info ">Add New</button>
                    </div>
                </div>

            }

        </div>
    </div>



</div>

Areas/Admin/Views/Breed/Delete.cshtml
@model AnimalShop.Models.Breed

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">


    <div class="card">
        <div class="card-body">
            <h3>Are you sure you want to delete this?</h3>
            <div>
                <h4>Breed</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.BreedType)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BreedType)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedAt)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatedAt)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UpdatedAt)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UpdatedAt)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>


        </div>
    </div>
</div>

Areas/Admin/Views/Breed/Details.cshtml
@model AnimalShop.Models.Breed

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">


    <div class="card">
        <div class="card-body">
            <div>
                <h4>Breed</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.BreedType)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BreedType)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedAt)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatedAt)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UpdatedAt)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UpdatedAt)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.BreedID }) |
                @Html.ActionLink("Back to List", "Index")
            </p>

        </div>
    </div>
</div>

Areas/Admin/Views/Breed/Edit.cshtml
@model AnimalShop.Models.Breed

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


<div class="page-wrapper">


    <div class="card">
        <div class="card-body">


            <div>
                <label>
                    @if (ViewBag.MSG != null)
                    {
                        <h3>    @ViewBag.MSG</h3>
                    }
                </label>
            </div>


            @using (Html.BeginForm("Edit", "Breed"))
            {



                @Html.AntiForgeryToken()

                @Html.HiddenFor(m => m.BreedID)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-3">
                        <label>Update Breed </label>
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-3">
                        @Html.EditorFor(model => model.BreedType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BreedType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        <button type="submit" class="btn btn-info ">Update</button>
                    </div>
                </div>

            }

        </div>
    </div>



</div>

Areas/Admin/Views/Breed/Index.cshtml
@model IEnumerable<AnimalShop.Models.Breed>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


<div class="page-wrapper">
    <div class="card">
        <div class="card-body">
            <div class="row">

                <div class="col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label>Search by breed</label>
                        <input type="text" class="form-control" placeholder="">
                    </div>
                </div>
                <div class="col-md-2 col-sm-2 col-12">
                    <div class="form-group">
                        <label>&nbsp;</label>
                        <div class="form-group">
                            <button type="submit" class="btn btn-danger waves-effect btn-block waves-light">Search</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 col-sm-2 col-12">
                    <div class="form-group">
                        <label>&nbsp;</label>
                        <div class="form-group">
                            <select class="form-control custom-select" data-placeholder="Export As" tabindex="1">
                                <option>Export As</option>
                                <option value="xlsx">Excel</option>
                                <option value="pdf">PDF</option>
                                <option value="csv">CSV</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 col-sm-2 col-12">
                    <div class="form-group">
                        <label>&nbsp;</label>
                        <div class="form-group">
                            <button type="button" class="btn btn-info waves-effect btn-block waves-light" data-toggle="modal" data-target="#addeditclientmodal">@Html.ActionLink("Create New", "Create") </button>
                        </div>
                    </div>
                </div>

            </div>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.BreedType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreatedAt)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UpdatedAt)
                    </th>
                    <th>Actions</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.BreedType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedAt)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UpdatedAt)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.BreedID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.BreedID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.BreedID })
                        </td>
                    </tr>
                }

            </table>



        </div>
    </div>
</div>